import type { AgentSamWidgetDefinition } from '@inneranimalmedia/agentsam-contracts/widgets';

/** Only widgets with working packaged renderers belong here. */
export const BUILTIN_WIDGET_DEFINITIONS = Object.freeze([
  Object.freeze({
    id: 'countdown',
    kind: 'countdown',
    title: 'Countdown',
    description: 'Absolute deadline timer for focus blocks and checkpoints.',
    icon: 'clock-3',
    category: 'utility',
    tags: ['focus', 'deadline', 'timer'],
    sizes: ['small', 'medium'] as const,
    availability: 'ready',
    ownerPackage: '@inneranimalmedia/agentsam-workbench',
    deeplink: '/widgets',
  } satisfies AgentSamWidgetDefinition),
] satisfies readonly AgentSamWidgetDefinition[]);

/** Curated metadata from the preserved 22-widget donor gallery.
 * Preview concepts are NOT placed in BUILTIN_WIDGET_DEFINITIONS until
 * a real packaged renderer and adapter exist.
 */
export const WIDGET_GALLERY_DEFINITIONS = Object.freeze([
  ...BUILTIN_WIDGET_DEFINITIONS,
  Object.freeze({
    id: 'clock',
    kind: 'clock',
    title: 'World & Precision Clock',
    description: 'UTC offset, timezone selector, local solar time, and seconds sweep',
    icon: 'clock',
    category: 'utility',
    tags: ['utility', 'time', 'world-clock', 'timezone'],
    sizes: ['small', 'medium'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-workbench',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'calculator',
    kind: 'calculator',
    title: 'Utility Calculator',
    description: 'Quick arithmetic and expression evaluator with history tape',
    icon: 'calculator',
    category: 'utility',
    tags: ['utility', 'math', 'calculator', 'history'],
    sizes: ['small', 'medium'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-workbench',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'quick-controls',
    kind: 'quick-controls',
    title: 'Quick Controls',
    description: 'Runtime toggles for turbo execution, telemetry stream, chimes, and atmosphere',
    icon: 'sliders-horizontal',
    category: 'utility',
    tags: ['utility', 'controls', 'settings', 'theme'],
    sizes: ['medium', 'large'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-workbench',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'metrics',
    kind: 'metrics',
    title: 'Operational Metrics',
    description: 'Throughput (req/s), latency p95, memory RSS, and event loop jitter',
    icon: 'activity',
    category: 'glance',
    tags: ['glance', 'metrics', 'telemetry', 'latency'],
    sizes: ['medium', 'large'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-analytics',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'jobs',
    kind: 'jobs',
    title: 'Scheduled Jobs',
    description: 'Cron scheduler status, next run projections, and trigger on-demand',
    icon: 'calendar-clock',
    category: 'glance',
    tags: ['glance', 'jobs', 'cron', 'batch'],
    sizes: ['medium', 'large'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-analytics',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'queues',
    kind: 'queues',
    title: 'Queue Depth',
    description: 'Inbound message backlog, priority distribution, and dead-letter count',
    icon: 'layers',
    category: 'glance',
    tags: ['glance', 'queues', 'backlog', 'throughput'],
    sizes: ['medium', 'large'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-queue-control',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'runtime-state',
    kind: 'runtime-state',
    title: 'Runtime State',
    description: 'Cluster health, active sandbox isolation, and node environment',
    icon: 'server',
    category: 'glance',
    tags: ['glance', 'runtime', 'health', 'cluster'],
    sizes: ['small', 'medium'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-work',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'cloudflare-observability',
    kind: 'cloudflare-observability',
    title: 'Cloudflare Worker Observability',
    description: 'Live Cloudflare Worker telemetry, CPU wall time, and Workers Observability MCP tools',
    icon: 'cloud',
    category: 'glance',
    tags: ['glance', 'cloudflare', 'workers', 'observability', 'telemetry'],
    sizes: ['medium', 'large'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-workbench',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'github-activity',
    kind: 'github-activity',
    title: 'GitHub Activity',
    description: 'Repository PR status, CI checks, branch sync, and commit feed',
    icon: 'git-branch',
    category: 'glance',
    tags: ['glance', 'github', 'git', 'pull-requests', 'ci'],
    sizes: ['small', 'medium'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-repository',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'launcher',
    kind: 'launcher',
    title: 'Command Launcher',
    description: 'Quick-access command launcher for agent tasks and weather queries',
    icon: 'compass',
    category: 'navigation',
    tags: ['navigation', 'launcher', 'quick-actions'],
    sizes: ['medium', 'large'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-workbench',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'recent-items',
    kind: 'recent-items',
    title: 'Recent Items',
    description: 'Historical weather dashboards, query sessions, and generated configs',
    icon: 'history',
    category: 'navigation',
    tags: ['navigation', 'recent', 'history', 'queries'],
    sizes: ['small', 'medium'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-workbench',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'shortcuts',
    kind: 'shortcuts',
    title: 'Studio Shortcuts',
    description: 'Keyboard navigation and rapid action shortcuts cheatsheet',
    icon: 'command',
    category: 'navigation',
    tags: ['navigation', 'shortcuts', 'keyboard', 'hotkeys'],
    sizes: ['small', 'medium'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-workbench',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'list',
    kind: 'list',
    title: 'Task Checklist',
    description: 'Interactive execution checklist with priority flags and status tracking',
    icon: 'list-checks',
    category: 'content',
    tags: ['content', 'tasks', 'checklist', 'todos'],
    sizes: ['medium', 'large'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-content',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'media',
    kind: 'media',
    title: 'Atmospheric Media',
    description: 'Live radar feed simulation and ambient acoustic atmospheric soundscapes',
    icon: 'radio',
    category: 'content',
    tags: ['content', 'media', 'radar', 'ambience'],
    sizes: ['medium', 'large'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-content',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'artifact-preview',
    kind: 'artifact-preview',
    title: 'Artifact Preview',
    description: 'Code and schema inspector for active widget contracts and dashboard configs',
    icon: 'file-code',
    category: 'content',
    tags: ['content', 'code', 'contracts', 'artifacts'],
    sizes: ['medium', 'large'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-content',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'active-run',
    kind: 'active-run',
    title: 'Active Run Inspector',
    description: 'Live agent execution step tracker, thought streaming, and tool calls',
    icon: 'play-circle',
    category: 'agent/runtime',
    tags: ['agent/runtime', 'agent', 'execution', 'streaming'],
    sizes: ['medium', 'large'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-work',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'token-cost-glance',
    kind: 'token-cost-glance',
    title: 'Token & Cost Glance',
    description: 'Real-time prompt/completion token counter and compute cost tally',
    icon: 'coins',
    category: 'agent/runtime',
    tags: ['agent/runtime', 'tokens', 'cost', 'metrics'],
    sizes: ['small', 'medium'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-analytics',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'queue-status',
    kind: 'queue-status',
    title: 'Agent Queue Status',
    description: 'Agent worker pipeline, concurrent subtasks, and backpressure',
    icon: 'network',
    category: 'agent/runtime',
    tags: ['agent/runtime', 'workers', 'concurrency', 'queues'],
    sizes: ['small', 'medium'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-queue-control',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'approvals',
    kind: 'approvals',
    title: 'Human Approvals',
    description: 'Pending external tool actions and cost thresholds requiring review',
    icon: 'shield-alert',
    category: 'agent/runtime',
    tags: ['agent/runtime', 'approvals', 'safety', 'human-in-the-loop'],
    sizes: ['medium', 'large'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-work',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'task-progress',
    kind: 'task-progress',
    title: 'Workflow Progress',
    description: 'Multi-stage workflow stepper with milestone timings and ETA',
    icon: 'git-commit',
    category: 'agent/runtime',
    tags: ['agent/runtime', 'progress', 'stepper', 'pipeline'],
    sizes: ['medium', 'large'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-goap',
  } satisfies AgentSamWidgetDefinition),
  Object.freeze({
    id: 'weather-dashboard-agent',
    kind: 'weather-dashboard-agent',
    title: 'Weather Dashboard Agent',
    description: 'Instant weather synthesis with KPI cards, dynamic charts, and satellite view',
    icon: 'cloud-sun',
    category: 'weather',
    tags: ['weather', 'agent', 'forecast', 'open-meteo'],
    sizes: ['large'] as const,
    availability: 'demo',
    ownerPackage: '@inneranimalmedia/agentsam-workbench',
  } satisfies AgentSamWidgetDefinition),
] satisfies readonly AgentSamWidgetDefinition[]);
