/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAgentsamRouteImport } from './routes/_app/agentsam'
import { Route as AppArtifactsRouteImport } from './routes/_app/artifacts'
import { Route as AppBrowseRouteImport } from './routes/_app/browse'
import { Route as AppCadRouteImport } from './routes/_app/cad'
import { Route as AppCliRouteImport } from './routes/_app/cli'
import { Route as AppCmsRouteImport } from './routes/_app/cms'
import { Route as AppFilesRouteImport } from './routes/_app/files'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppShipRouteImport } from './routes/_app/ship'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCloudflareRouteImport } from './routes/api/cloudflare'
import { Route as ApiGithubRouteImport } from './routes/api/github'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/_app/settings/integrations'
import { Route as AppSettingsKeysRouteImport } from './routes/_app/settings/keys'
import { Route as AppTrailsIndexRouteImport } from './routes/_app/trails/index'
import { Route as AppTrailsTrailIdRouteImport } from './routes/_app/trails/$trailId'
import { Route as ApiLlmInventoryRouteImport } from './routes/api/llm.inventory'
import { Route as AppAgentsamAppsCadRouteImport } from './routes/_app/agentsam.apps.cad'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentsamRoute = AppAgentsamRouteImport.update({
  id: '/agentsam',
  path: '/agentsam',
  getParentRoute: () => AppRoute,
} as any)
const AppArtifactsRoute = AppArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseRoute = AppBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AppRoute,
} as any)
const AppCadRoute = AppCadRouteImport.update({
  id: '/cad',
  path: '/cad',
  getParentRoute: () => AppRoute,
} as any)
const AppCliRoute = AppCliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => AppRoute,
} as any)
const AppCmsRoute = AppCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppShipRoute = AppShipRouteImport.update({
  id: '/ship',
  path: '/ship',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudflareRoute = ApiCloudflareRouteImport.update({
  id: '/api/cloudflare',
  path: '/api/cloudflare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubRoute = ApiGithubRouteImport.update({
  id: '/api/github',
  path: '/api/github',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsKeysRoute = AppSettingsKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppTrailsIndexRoute = AppTrailsIndexRouteImport.update({
  id: '/trails/',
  path: '/trails/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrailsTrailIdRoute = AppTrailsTrailIdRouteImport.update({
  id: '/trails/$trailId',
  path: '/trails/$trailId',
  getParentRoute: () => AppRoute,
} as any)
const ApiLlmInventoryRoute = ApiLlmInventoryRouteImport.update({
  id: '/api/llm/inventory',
  path: '/api/llm/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentsamAppsCadRoute = AppAgentsamAppsCadRouteImport.update({
  id: '/apps/cad',
  path: '/apps/cad',
  getParentRoute: () => AppAgentsamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentsam': typeof AppAgentsamRouteWithChildren
  '/artifacts': typeof AppArtifactsRoute
  '/browse': typeof AppBrowseRoute
  '/cad': typeof AppCadRoute
  '/cli': typeof AppCliRoute
  '/cms': typeof AppCmsRoute
  '/files': typeof AppFilesRoute
  '/projects': typeof AppProjectsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/ship': typeof AppShipRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cloudflare': typeof ApiCloudflareRoute
  '/api/github': typeof ApiGithubRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/keys': typeof AppSettingsKeysRoute
  '/trails/$trailId': typeof AppTrailsTrailIdRoute
  '/api/llm/inventory': typeof ApiLlmInventoryRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/trails/': typeof AppTrailsIndexRoute
  '/agentsam/apps/cad': typeof AppAgentsamAppsCadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentsam': typeof AppAgentsamRouteWithChildren
  '/artifacts': typeof AppArtifactsRoute
  '/browse': typeof AppBrowseRoute
  '/cad': typeof AppCadRoute
  '/cli': typeof AppCliRoute
  '/cms': typeof AppCmsRoute
  '/files': typeof AppFilesRoute
  '/projects': typeof AppProjectsRoute
  '/ship': typeof AppShipRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cloudflare': typeof ApiCloudflareRoute
  '/api/github': typeof ApiGithubRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/keys': typeof AppSettingsKeysRoute
  '/trails/$trailId': typeof AppTrailsTrailIdRoute
  '/api/llm/inventory': typeof ApiLlmInventoryRoute
  '/settings': typeof AppSettingsIndexRoute
  '/trails': typeof AppTrailsIndexRoute
  '/agentsam/apps/cad': typeof AppAgentsamAppsCadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/agentsam': typeof AppAgentsamRouteWithChildren
  '/_app/artifacts': typeof AppArtifactsRoute
  '/_app/browse': typeof AppBrowseRoute
  '/_app/cad': typeof AppCadRoute
  '/_app/cli': typeof AppCliRoute
  '/_app/cms': typeof AppCmsRoute
  '/_app/files': typeof AppFilesRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/ship': typeof AppShipRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cloudflare': typeof ApiCloudflareRoute
  '/api/github': typeof ApiGithubRoute
  '/_app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/_app/settings/keys': typeof AppSettingsKeysRoute
  '/_app/trails/$trailId': typeof AppTrailsTrailIdRoute
  '/api/llm/inventory': typeof ApiLlmInventoryRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/trails/': typeof AppTrailsIndexRoute
  '/_app/agentsam/apps/cad': typeof AppAgentsamAppsCadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentsam'
    | '/artifacts'
    | '/browse'
    | '/cad'
    | '/cli'
    | '/cms'
    | '/files'
    | '/projects'
    | '/settings'
    | '/ship'
    | '/api/chat'
    | '/api/cloudflare'
    | '/api/github'
    | '/settings/integrations'
    | '/settings/keys'
    | '/trails/$trailId'
    | '/api/llm/inventory'
    | '/settings/'
    | '/trails/'
    | '/agentsam/apps/cad'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentsam'
    | '/artifacts'
    | '/browse'
    | '/cad'
    | '/cli'
    | '/cms'
    | '/files'
    | '/projects'
    | '/ship'
    | '/api/chat'
    | '/api/cloudflare'
    | '/api/github'
    | '/settings/integrations'
    | '/settings/keys'
    | '/trails/$trailId'
    | '/api/llm/inventory'
    | '/settings'
    | '/trails'
    | '/agentsam/apps/cad'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/agentsam'
    | '/_app/artifacts'
    | '/_app/browse'
    | '/_app/cad'
    | '/_app/cli'
    | '/_app/cms'
    | '/_app/files'
    | '/_app/projects'
    | '/_app/settings'
    | '/_app/ship'
    | '/api/chat'
    | '/api/cloudflare'
    | '/api/github'
    | '/_app/settings/integrations'
    | '/_app/settings/keys'
    | '/_app/trails/$trailId'
    | '/api/llm/inventory'
    | '/_app/settings/'
    | '/_app/trails/'
    | '/_app/agentsam/apps/cad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiCloudflareRoute: typeof ApiCloudflareRoute
  ApiGithubRoute: typeof ApiGithubRoute
  ApiLlmInventoryRoute: typeof ApiLlmInventoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agentsam': {
      id: '/_app/agentsam'
      path: '/agentsam'
      fullPath: '/agentsam'
      preLoaderRoute: typeof AppAgentsamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/artifacts': {
      id: '/_app/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof AppArtifactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse': {
      id: '/_app/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AppBrowseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cad': {
      id: '/_app/cad'
      path: '/cad'
      fullPath: '/cad'
      preLoaderRoute: typeof AppCadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cli': {
      id: '/_app/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof AppCliRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cms': {
      id: '/_app/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof AppCmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/files': {
      id: '/_app/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ship': {
      id: '/_app/ship'
      path: '/ship'
      fullPath: '/ship'
      preLoaderRoute: typeof AppShipRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudflare': {
      id: '/api/cloudflare'
      path: '/api/cloudflare'
      fullPath: '/api/cloudflare'
      preLoaderRoute: typeof ApiCloudflareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github': {
      id: '/api/github'
      path: '/api/github'
      fullPath: '/api/github'
      preLoaderRoute: typeof ApiGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/integrations': {
      id: '/_app/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/keys': {
      id: '/_app/settings/keys'
      path: '/keys'
      fullPath: '/settings/keys'
      preLoaderRoute: typeof AppSettingsKeysRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/trails/': {
      id: '/_app/trails/'
      path: '/trails'
      fullPath: '/trails/'
      preLoaderRoute: typeof AppTrailsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trails/$trailId': {
      id: '/_app/trails/$trailId'
      path: '/trails/$trailId'
      fullPath: '/trails/$trailId'
      preLoaderRoute: typeof AppTrailsTrailIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/llm/inventory': {
      id: '/api/llm/inventory'
      path: '/api/llm/inventory'
      fullPath: '/api/llm/inventory'
      preLoaderRoute: typeof ApiLlmInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agentsam/apps/cad': {
      id: '/_app/agentsam/apps/cad'
      path: '/apps/cad'
      fullPath: '/agentsam/apps/cad'
      preLoaderRoute: typeof AppAgentsamAppsCadRouteImport
      parentRoute: typeof AppAgentsamRoute
    }
  }
}

interface AppAgentsamRouteChildren {
  AppAgentsamAppsCadRoute: typeof AppAgentsamAppsCadRoute
}

const AppAgentsamRouteChildren: AppAgentsamRouteChildren = {
  AppAgentsamAppsCadRoute: AppAgentsamAppsCadRoute,
}

const AppAgentsamRouteWithChildren = AppAgentsamRoute._addFileChildren(
  AppAgentsamRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsKeysRoute: typeof AppSettingsKeysRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsKeysRoute: AppSettingsKeysRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAgentsamRoute: typeof AppAgentsamRouteWithChildren
  AppArtifactsRoute: typeof AppArtifactsRoute
  AppBrowseRoute: typeof AppBrowseRoute
  AppCadRoute: typeof AppCadRoute
  AppCliRoute: typeof AppCliRoute
  AppCmsRoute: typeof AppCmsRoute
  AppFilesRoute: typeof AppFilesRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppShipRoute: typeof AppShipRoute
  AppTrailsTrailIdRoute: typeof AppTrailsTrailIdRoute
  AppTrailsIndexRoute: typeof AppTrailsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsamRoute: AppAgentsamRouteWithChildren,
  AppArtifactsRoute: AppArtifactsRoute,
  AppBrowseRoute: AppBrowseRoute,
  AppCadRoute: AppCadRoute,
  AppCliRoute: AppCliRoute,
  AppCmsRoute: AppCmsRoute,
  AppFilesRoute: AppFilesRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppShipRoute: AppShipRoute,
  AppTrailsTrailIdRoute: AppTrailsTrailIdRoute,
  AppTrailsIndexRoute: AppTrailsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiCloudflareRoute: ApiCloudflareRoute,
  ApiGithubRoute: ApiGithubRoute,
  ApiLlmInventoryRoute: ApiLlmInventoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
