/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appsAgentsamRouteImport } from './routes/(apps)/agentsam'
import { Route as appsArtifactsRouteImport } from './routes/(apps)/artifacts'
import { Route as appsBrowseRouteImport } from './routes/(apps)/browse'
import { Route as appsCadRouteImport } from './routes/(apps)/cad'
import { Route as appsCliRouteImport } from './routes/(apps)/cli'
import { Route as appsCmsRouteImport } from './routes/(apps)/cms'
import { Route as appsDatabaseRouteImport } from './routes/(apps)/database'
import { Route as appsFilesRouteImport } from './routes/(apps)/files'
import { Route as appsProjectsRouteImport } from './routes/(apps)/projects'
import { Route as appsSettingsRouteImport } from './routes/(apps)/settings'
import { Route as appsShipRouteImport } from './routes/(apps)/ship'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCloudflareRouteImport } from './routes/api/cloudflare'
import { Route as ApiGithubRouteImport } from './routes/api/github'
import { Route as appsSettingsIndexRouteImport } from './routes/(apps)/settings/index'
import { Route as appsSettingsUnitRouteImport } from './routes/(apps)/settings/$unit'
import { Route as appsSettingsIntegrationsRouteImport } from './routes/(apps)/settings/integrations'
import { Route as appsSettingsKeysRouteImport } from './routes/(apps)/settings/keys'
import { Route as appsSettingsThemesRouteImport } from './routes/(apps)/settings/themes'
import { Route as appsTrailsIndexRouteImport } from './routes/(apps)/trails/index'
import { Route as appsTrailsTrailIdRouteImport } from './routes/(apps)/trails/$trailId'
import { Route as ApiLlmInventoryRouteImport } from './routes/api/llm.inventory'
import { Route as appsAgentsamAppsCadRouteImport } from './routes/(apps)/agentsam.apps.cad'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appsAgentsamRoute = appsAgentsamRouteImport.update({
  id: '/(apps)/agentsam',
  path: '/agentsam',
  getParentRoute: () => rootRouteImport,
} as any)
const appsArtifactsRoute = appsArtifactsRouteImport.update({
  id: '/(apps)/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const appsBrowseRoute = appsBrowseRouteImport.update({
  id: '/(apps)/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const appsCadRoute = appsCadRouteImport.update({
  id: '/(apps)/cad',
  path: '/cad',
  getParentRoute: () => rootRouteImport,
} as any)
const appsCliRoute = appsCliRouteImport.update({
  id: '/(apps)/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const appsCmsRoute = appsCmsRouteImport.update({
  id: '/(apps)/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const appsDatabaseRoute = appsDatabaseRouteImport.update({
  id: '/(apps)/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const appsFilesRoute = appsFilesRouteImport.update({
  id: '/(apps)/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const appsProjectsRoute = appsProjectsRouteImport.update({
  id: '/(apps)/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const appsSettingsRoute = appsSettingsRouteImport.update({
  id: '/(apps)/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const appsShipRoute = appsShipRouteImport.update({
  id: '/(apps)/ship',
  path: '/ship',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudflareRoute = ApiCloudflareRouteImport.update({
  id: '/api/cloudflare',
  path: '/api/cloudflare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubRoute = ApiGithubRouteImport.update({
  id: '/api/github',
  path: '/api/github',
  getParentRoute: () => rootRouteImport,
} as any)
const appsSettingsIndexRoute = appsSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appsSettingsRoute,
} as any)
const appsSettingsUnitRoute = appsSettingsUnitRouteImport.update({
  id: '/$unit',
  path: '/$unit',
  getParentRoute: () => appsSettingsRoute,
} as any)
const appsSettingsIntegrationsRoute =
  appsSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => appsSettingsRoute,
  } as any)
const appsSettingsKeysRoute = appsSettingsKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => appsSettingsRoute,
} as any)
const appsSettingsThemesRoute = appsSettingsThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => appsSettingsRoute,
} as any)
const appsTrailsIndexRoute = appsTrailsIndexRouteImport.update({
  id: '/(apps)/trails/',
  path: '/trails/',
  getParentRoute: () => rootRouteImport,
} as any)
const appsTrailsTrailIdRoute = appsTrailsTrailIdRouteImport.update({
  id: '/(apps)/trails/$trailId',
  path: '/trails/$trailId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmInventoryRoute = ApiLlmInventoryRouteImport.update({
  id: '/api/llm/inventory',
  path: '/api/llm/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const appsAgentsamAppsCadRoute = appsAgentsamAppsCadRouteImport.update({
  id: '/apps/cad',
  path: '/apps/cad',
  getParentRoute: () => appsAgentsamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentsam': typeof appsAgentsamRouteWithChildren
  '/artifacts': typeof appsArtifactsRoute
  '/browse': typeof appsBrowseRoute
  '/cad': typeof appsCadRoute
  '/cli': typeof appsCliRoute
  '/cms': typeof appsCmsRoute
  '/database': typeof appsDatabaseRoute
  '/files': typeof appsFilesRoute
  '/projects': typeof appsProjectsRoute
  '/settings': typeof appsSettingsRouteWithChildren
  '/ship': typeof appsShipRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cloudflare': typeof ApiCloudflareRoute
  '/api/github': typeof ApiGithubRoute
  '/settings/$unit': typeof appsSettingsUnitRoute
  '/settings/integrations': typeof appsSettingsIntegrationsRoute
  '/settings/keys': typeof appsSettingsKeysRoute
  '/settings/themes': typeof appsSettingsThemesRoute
  '/trails/$trailId': typeof appsTrailsTrailIdRoute
  '/api/llm/inventory': typeof ApiLlmInventoryRoute
  '/settings/': typeof appsSettingsIndexRoute
  '/trails/': typeof appsTrailsIndexRoute
  '/agentsam/apps/cad': typeof appsAgentsamAppsCadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentsam': typeof appsAgentsamRouteWithChildren
  '/artifacts': typeof appsArtifactsRoute
  '/browse': typeof appsBrowseRoute
  '/cad': typeof appsCadRoute
  '/cli': typeof appsCliRoute
  '/cms': typeof appsCmsRoute
  '/database': typeof appsDatabaseRoute
  '/files': typeof appsFilesRoute
  '/projects': typeof appsProjectsRoute
  '/ship': typeof appsShipRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cloudflare': typeof ApiCloudflareRoute
  '/api/github': typeof ApiGithubRoute
  '/settings/$unit': typeof appsSettingsUnitRoute
  '/settings/integrations': typeof appsSettingsIntegrationsRoute
  '/settings/keys': typeof appsSettingsKeysRoute
  '/settings/themes': typeof appsSettingsThemesRoute
  '/trails/$trailId': typeof appsTrailsTrailIdRoute
  '/api/llm/inventory': typeof ApiLlmInventoryRoute
  '/settings': typeof appsSettingsIndexRoute
  '/trails': typeof appsTrailsIndexRoute
  '/agentsam/apps/cad': typeof appsAgentsamAppsCadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(apps)/agentsam': typeof appsAgentsamRouteWithChildren
  '/(apps)/artifacts': typeof appsArtifactsRoute
  '/(apps)/browse': typeof appsBrowseRoute
  '/(apps)/cad': typeof appsCadRoute
  '/(apps)/cli': typeof appsCliRoute
  '/(apps)/cms': typeof appsCmsRoute
  '/(apps)/database': typeof appsDatabaseRoute
  '/(apps)/files': typeof appsFilesRoute
  '/(apps)/projects': typeof appsProjectsRoute
  '/(apps)/settings': typeof appsSettingsRouteWithChildren
  '/(apps)/ship': typeof appsShipRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cloudflare': typeof ApiCloudflareRoute
  '/api/github': typeof ApiGithubRoute
  '/(apps)/settings/$unit': typeof appsSettingsUnitRoute
  '/(apps)/settings/integrations': typeof appsSettingsIntegrationsRoute
  '/(apps)/settings/keys': typeof appsSettingsKeysRoute
  '/(apps)/settings/themes': typeof appsSettingsThemesRoute
  '/(apps)/trails/$trailId': typeof appsTrailsTrailIdRoute
  '/api/llm/inventory': typeof ApiLlmInventoryRoute
  '/(apps)/settings/': typeof appsSettingsIndexRoute
  '/(apps)/trails/': typeof appsTrailsIndexRoute
  '/(apps)/agentsam/apps/cad': typeof appsAgentsamAppsCadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentsam'
    | '/artifacts'
    | '/browse'
    | '/cad'
    | '/cli'
    | '/cms'
    | '/database'
    | '/files'
    | '/projects'
    | '/settings'
    | '/ship'
    | '/api/chat'
    | '/api/cloudflare'
    | '/api/github'
    | '/settings/$unit'
    | '/settings/integrations'
    | '/settings/keys'
    | '/settings/themes'
    | '/trails/$trailId'
    | '/api/llm/inventory'
    | '/settings/'
    | '/trails/'
    | '/agentsam/apps/cad'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentsam'
    | '/artifacts'
    | '/browse'
    | '/cad'
    | '/cli'
    | '/cms'
    | '/database'
    | '/files'
    | '/projects'
    | '/ship'
    | '/api/chat'
    | '/api/cloudflare'
    | '/api/github'
    | '/settings/$unit'
    | '/settings/integrations'
    | '/settings/keys'
    | '/settings/themes'
    | '/trails/$trailId'
    | '/api/llm/inventory'
    | '/settings'
    | '/trails'
    | '/agentsam/apps/cad'
  id:
    | '__root__'
    | '/'
    | '/(apps)/agentsam'
    | '/(apps)/artifacts'
    | '/(apps)/browse'
    | '/(apps)/cad'
    | '/(apps)/cli'
    | '/(apps)/cms'
    | '/(apps)/database'
    | '/(apps)/files'
    | '/(apps)/projects'
    | '/(apps)/settings'
    | '/(apps)/ship'
    | '/api/chat'
    | '/api/cloudflare'
    | '/api/github'
    | '/(apps)/settings/$unit'
    | '/(apps)/settings/integrations'
    | '/(apps)/settings/keys'
    | '/(apps)/settings/themes'
    | '/(apps)/trails/$trailId'
    | '/api/llm/inventory'
    | '/(apps)/settings/'
    | '/(apps)/trails/'
    | '/(apps)/agentsam/apps/cad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appsAgentsamRoute: typeof appsAgentsamRouteWithChildren
  appsArtifactsRoute: typeof appsArtifactsRoute
  appsBrowseRoute: typeof appsBrowseRoute
  appsCadRoute: typeof appsCadRoute
  appsCliRoute: typeof appsCliRoute
  appsCmsRoute: typeof appsCmsRoute
  appsDatabaseRoute: typeof appsDatabaseRoute
  appsFilesRoute: typeof appsFilesRoute
  appsProjectsRoute: typeof appsProjectsRoute
  appsSettingsRoute: typeof appsSettingsRouteWithChildren
  appsShipRoute: typeof appsShipRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCloudflareRoute: typeof ApiCloudflareRoute
  ApiGithubRoute: typeof ApiGithubRoute
  appsTrailsTrailIdRoute: typeof appsTrailsTrailIdRoute
  ApiLlmInventoryRoute: typeof ApiLlmInventoryRoute
  appsTrailsIndexRoute: typeof appsTrailsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/agentsam': {
      id: '/(apps)/agentsam'
      path: '/agentsam'
      fullPath: '/agentsam'
      preLoaderRoute: typeof appsAgentsamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/artifacts': {
      id: '/(apps)/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof appsArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/browse': {
      id: '/(apps)/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof appsBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/cad': {
      id: '/(apps)/cad'
      path: '/cad'
      fullPath: '/cad'
      preLoaderRoute: typeof appsCadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/cli': {
      id: '/(apps)/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof appsCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/cms': {
      id: '/(apps)/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof appsCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/database': {
      id: '/(apps)/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof appsDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/files': {
      id: '/(apps)/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof appsFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/projects': {
      id: '/(apps)/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof appsProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/settings': {
      id: '/(apps)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/ship': {
      id: '/(apps)/ship'
      path: '/ship'
      fullPath: '/ship'
      preLoaderRoute: typeof appsShipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudflare': {
      id: '/api/cloudflare'
      path: '/api/cloudflare'
      fullPath: '/api/cloudflare'
      preLoaderRoute: typeof ApiCloudflareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github': {
      id: '/api/github'
      path: '/api/github'
      fullPath: '/api/github'
      preLoaderRoute: typeof ApiGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/settings/': {
      id: '/(apps)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof appsSettingsIndexRouteImport
      parentRoute: typeof appsSettingsRoute
    }
    '/(apps)/settings/$unit': {
      id: '/(apps)/settings/$unit'
      path: '/$unit'
      fullPath: '/settings/$unit'
      preLoaderRoute: typeof appsSettingsUnitRouteImport
      parentRoute: typeof appsSettingsRoute
    }
    '/(apps)/settings/integrations': {
      id: '/(apps)/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof appsSettingsIntegrationsRouteImport
      parentRoute: typeof appsSettingsRoute
    }
    '/(apps)/settings/keys': {
      id: '/(apps)/settings/keys'
      path: '/keys'
      fullPath: '/settings/keys'
      preLoaderRoute: typeof appsSettingsKeysRouteImport
      parentRoute: typeof appsSettingsRoute
    }
    '/(apps)/settings/themes': {
      id: '/(apps)/settings/themes'
      path: '/themes'
      fullPath: '/settings/themes'
      preLoaderRoute: typeof appsSettingsThemesRouteImport
      parentRoute: typeof appsSettingsRoute
    }
    '/(apps)/trails/': {
      id: '/(apps)/trails/'
      path: '/trails'
      fullPath: '/trails/'
      preLoaderRoute: typeof appsTrailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/trails/$trailId': {
      id: '/(apps)/trails/$trailId'
      path: '/trails/$trailId'
      fullPath: '/trails/$trailId'
      preLoaderRoute: typeof appsTrailsTrailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm/inventory': {
      id: '/api/llm/inventory'
      path: '/api/llm/inventory'
      fullPath: '/api/llm/inventory'
      preLoaderRoute: typeof ApiLlmInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(apps)/agentsam/apps/cad': {
      id: '/(apps)/agentsam/apps/cad'
      path: '/apps/cad'
      fullPath: '/agentsam/apps/cad'
      preLoaderRoute: typeof appsAgentsamAppsCadRouteImport
      parentRoute: typeof appsAgentsamRoute
    }
  }
}

interface appsAgentsamRouteChildren {
  appsAgentsamAppsCadRoute: typeof appsAgentsamAppsCadRoute
}

const appsAgentsamRouteChildren: appsAgentsamRouteChildren = {
  appsAgentsamAppsCadRoute: appsAgentsamAppsCadRoute,
}

const appsAgentsamRouteWithChildren = appsAgentsamRoute._addFileChildren(
  appsAgentsamRouteChildren,
)

interface appsSettingsRouteChildren {
  appsSettingsUnitRoute: typeof appsSettingsUnitRoute
  appsSettingsIntegrationsRoute: typeof appsSettingsIntegrationsRoute
  appsSettingsKeysRoute: typeof appsSettingsKeysRoute
  appsSettingsThemesRoute: typeof appsSettingsThemesRoute
  appsSettingsIndexRoute: typeof appsSettingsIndexRoute
}

const appsSettingsRouteChildren: appsSettingsRouteChildren = {
  appsSettingsUnitRoute: appsSettingsUnitRoute,
  appsSettingsIntegrationsRoute: appsSettingsIntegrationsRoute,
  appsSettingsKeysRoute: appsSettingsKeysRoute,
  appsSettingsThemesRoute: appsSettingsThemesRoute,
  appsSettingsIndexRoute: appsSettingsIndexRoute,
}

const appsSettingsRouteWithChildren = appsSettingsRoute._addFileChildren(
  appsSettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appsAgentsamRoute: appsAgentsamRouteWithChildren,
  appsArtifactsRoute: appsArtifactsRoute,
  appsBrowseRoute: appsBrowseRoute,
  appsCadRoute: appsCadRoute,
  appsCliRoute: appsCliRoute,
  appsCmsRoute: appsCmsRoute,
  appsDatabaseRoute: appsDatabaseRoute,
  appsFilesRoute: appsFilesRoute,
  appsProjectsRoute: appsProjectsRoute,
  appsSettingsRoute: appsSettingsRouteWithChildren,
  appsShipRoute: appsShipRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCloudflareRoute: ApiCloudflareRoute,
  ApiGithubRoute: ApiGithubRoute,
  appsTrailsTrailIdRoute: appsTrailsTrailIdRoute,
  ApiLlmInventoryRoute: ApiLlmInventoryRoute,
  appsTrailsIndexRoute: appsTrailsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
