import type { ContentAsset } from "../core/asset.js";
import type { SemanticEnrichment } from "../core/intelligence.js";

export * from "./machine-pass.js";
export * from "./classify.js";
export * from "./semantic-name.js";
export * from "./tags.js";
export * from "./alt.js";
export * from "./seo.js";
export * from "./duplicate-detect.js";
export * from "./brand-match.js";
export * from "./recommendations.js";

/**
 * Pluggable semantic enrichment boundary. The package never calls an
 * LLM itself; hosts wire Workers AI / AgentSam / any model here.
 * Machine facts run first — the enricher receives an asset whose
 * intelligence.machine is already populated.
 */
export interface SemanticEnricher {
  enrich(asset: ContentAsset): Promise<SemanticEnrichment>;
}

/**
 * @deprecated Prefer ContentKnowledgeAdapter from ../contracts/knowledge.js.
 * Kept as a thin indexing sink for migration; never the SSOT for meaning.
 */
export interface RagSink {
  index(document: {
    accountId: string;
    assetId: string;
    text: string;
    metadata: Record<string, unknown>;
  }): Promise<{ documentId: string; index: string }>;
}

export {
  type ContentKnowledgeAdapter,
  type ContentKnowledgeDocument,
  type ContentKnowledgeQuery,
  type ContentKnowledgeResult,
  type ContentKnowledgeCapabilities,
  type IndexReceipt,
  noopKnowledgeAdapter,
  hybridKnowledgeAdapter,
} from "../contracts/knowledge.js";

import type { ContentKnowledgeAdapter } from "../contracts/knowledge.js";
import { noopKnowledgeAdapter } from "../contracts/knowledge.js";

/** Adapt legacy RagSink into the neutral knowledge contract. */
export function knowledgeFromRagSink(rag: RagSink): ContentKnowledgeAdapter {
  return {
    capabilities: () => ({
      index: true,
      remove: false,
      search: false,
      enrich: false,
      backends: ["legacy-rag-sink"],
    }),
    async index(document) {
      const result = await rag.index({
        accountId: document.accountId,
        assetId: document.assetId,
        text: document.text,
        metadata: document.metadata,
      });
      return {
        documentId: result.documentId,
        index: result.index,
        indexedAt: new Date().toISOString(),
      };
    },
    async remove() {},
    async search() {
      return [];
    },
  };
}

export function resolveKnowledgeAdapter(opts: {
  knowledge?: ContentKnowledgeAdapter;
  rag?: RagSink;
}): ContentKnowledgeAdapter {
  if (opts.knowledge) return opts.knowledge;
  if (opts.rag) return knowledgeFromRagSink(opts.rag);
  return noopKnowledgeAdapter;
}

/** Build the textual RAG document for an asset (facts-first, no binary). */
export function ragDocumentText(asset: ContentAsset): string {
  const lines: string[] = [
    `kind: ${asset.kind}`,
    `state: ${asset.state}`,
    `origin: ${asset.origin}`,
  ];
  if (asset.title) lines.push(`title: ${asset.title}`);
  if (asset.semanticAlias) lines.push(`alias: ${asset.semanticAlias}`);
  if (asset.alt) lines.push(`alt: ${asset.alt}`);
  if (asset.caption) lines.push(`caption: ${asset.caption}`);
  if (asset.role) lines.push(`role: ${asset.role}`);
  if (asset.tags.length) lines.push(`tags: ${asset.tags.join(", ")}`);
  if (asset.brandId) lines.push(`brand: ${asset.brandId}`);
  if (asset.projectId) lines.push(`project: ${asset.projectId}`);
  const s = asset.intelligence?.semantic;
  if (s?.subject) lines.push(`subject: ${s.subject}`);
  if (s?.description) lines.push(`description: ${s.description}`);
  if (s?.qualityConcerns?.length) lines.push(`quality concerns: ${s.qualityConcerns.join("; ")}`);
  if (asset.rating !== undefined) lines.push(`human rating: ${asset.rating}`);
  const liveUsage = asset.usage.filter((u) => u.live && !u.detachedAt);
  if (liveUsage.length) {
    lines.push(`used by: ${liveUsage.map((u) => `${u.app}/${u.surface}`).join(", ")}`);
  }
  const gen = asset.provenance.generation;
  if (gen?.model) lines.push(`generated by: ${gen.model}`);
  if (gen?.prompt) lines.push(`prompt: ${gen.prompt}`);
  return lines.join("\n");
}
