import path from 'node:path';
import { createLocalEngineRegistry } from '../local-engine/index.js';
import { auditLocalCompute } from '../local-engine/audit.js';
import { auditAssets } from '../local-engine/assets.js';
import { benchmarkEngine } from '../local-engine/benchmark.js';

function parse(argv = []) { const out = { action: argv[0] || 'status', engine: null, model: null, json: argv.includes('--json'), runs: 1, cwd: process.cwd() }; for (let i = 1; i < argv.length; i += 1) { const arg = argv[i]; if (arg === '--model') out.model = argv[++i]; else if (arg === '--runs') out.runs = Number(argv[++i]) || 1; else if (arg === '--cwd') out.cwd = path.resolve(argv[++i] || out.cwd); else if (arg === '--engine') out.engine = argv[++i]; } return out; }
function emit(value, json) { if (json) console.log(JSON.stringify(value)); else console.log(JSON.stringify(value, null, 2)); }
function usage() { return `agentsam engine <status|audit|benchmark|assets> [options]\n\n  status                 Discover local engines and models\n  audit                  Read-only Apple hardware + engine inventory\n  benchmark              Measure a selected engine/model\n  assets audit           Audit adopted model references without copying weights\n\n  --engine <id>          ollama | mlx-lm | llama.cpp\n  --model <id>           Engine model identifier\n  --runs <n>             Benchmark repetitions (default 1)\n  --cwd <path>           Project context\n  --json                 Machine-readable output\n`; }
export async function runEngine(argv = []) { const args = parse(argv); if (args.action === '--help' || args.action === 'help') { console.log(usage()); return 0; } const registry = createLocalEngineRegistry(); if (args.action === 'status') { emit({ schema_version: 'agentsam.local-engine.v1', engines: await registry.discover() }, args.json); return 0; } if (args.action === 'audit') { emit(auditLocalCompute(), args.json); return 0; } if (args.action === 'assets' && argv[1] === 'audit') { emit(auditAssets(), args.json); return 0; } if (args.action === 'benchmark') { if (!args.engine || !args.model) throw new Error('engine benchmark requires --engine <id> and --model <id>'); const result = await benchmarkEngine(registry.get(args.engine), { model: args.model, runs: args.runs }); emit(result, args.json); return 0; } console.log(usage()); return 1; }
