-- Canonical portable plugin/tool registry for AgentSam applications.
-- OAuth ciphertext remains in provider-owned connection tables encrypted by
-- the application's own vault key; these rows contain metadata and evidence.

CREATE TABLE IF NOT EXISTS agentsam_plugins (
  id TEXT PRIMARY KEY DEFAULT ('plg_' || lower(hex(randomblob(8)))),
  account_id TEXT NOT NULL,
  plugin_key TEXT NOT NULL,
  provider_key TEXT NOT NULL,
  installation_key TEXT NOT NULL DEFAULT 'default',
  environment TEXT NOT NULL DEFAULT 'production' CHECK (environment IN ('development','preview','staging','production')),
  plugin_kind TEXT NOT NULL CHECK (plugin_kind IN ('mcp','api','oauth','native','webhook','database','storage','ai')),
  category TEXT NOT NULL DEFAULT 'integration',
  display_name TEXT NOT NULL,
  short_name TEXT,
  description TEXT,
  mention_aliases_json TEXT NOT NULL DEFAULT '[]',
  endpoint_url TEXT,
  transport TEXT NOT NULL CHECK (transport IN ('remote_jsonrpc','iam_mcp_catalog','http_rest','http_graphql','webhook','workers_binding','native','none')),
  auth_type TEXT NOT NULL DEFAULT 'none' CHECK (auth_type IN ('none','bridge','oauth','oauth_via_iam','bearer_secret','api_key_secret','workers_binding')),
  secret_ref TEXT,
  oauth_connect_url TEXT,
  capabilities_json TEXT NOT NULL DEFAULT '[]',
  tool_lanes_json TEXT NOT NULL DEFAULT '[]',
  resource_scope_json TEXT NOT NULL DEFAULT '{}',
  config_json TEXT NOT NULL DEFAULT '{}',
  metadata_json TEXT NOT NULL DEFAULT '{}',
  icon_url TEXT,
  icon_dark_url TEXT,
  icon_alt TEXT,
  icon_fit TEXT NOT NULL DEFAULT 'contain' CHECK (icon_fit IN ('contain','cover')),
  composer_visible INTEGER NOT NULL DEFAULT 1 CHECK (composer_visible IN (0,1)),
  settings_visible INTEGER NOT NULL DEFAULT 1 CHECK (settings_visible IN (0,1)),
  sort_priority INTEGER NOT NULL DEFAULT 50,
  is_enabled INTEGER NOT NULL DEFAULT 1 CHECK (is_enabled IN (0,1)),
  setup_status TEXT NOT NULL DEFAULT 'unconfigured' CHECK (setup_status IN ('unconfigured','configured','connected','disabled')),
  health_strategy TEXT NOT NULL DEFAULT 'adapter' CHECK (health_strategy IN ('none','adapter','mcp_ping','oauth_probe','provider_probe')),
  health_status TEXT NOT NULL DEFAULT 'unknown' CHECK (health_status IN ('unknown','healthy','degraded','unhealthy','unreachable','auth_error','disabled')),
  last_health_at INTEGER,
  last_healthy_at INTEGER,
  consecutive_failures INTEGER NOT NULL DEFAULT 0,
  avg_latency_ms REAL,
  error_rate_24h REAL NOT NULL DEFAULT 0,
  last_error_code TEXT,
  last_error_message TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch()),
  UNIQUE (account_id, environment, plugin_key, installation_key)
);

CREATE TABLE IF NOT EXISTS agentsam_plugin_health_checks (
  id TEXT PRIMARY KEY DEFAULT ('plgh_' || lower(hex(randomblob(8)))),
  plugin_id TEXT NOT NULL REFERENCES agentsam_plugins(id) ON DELETE CASCADE,
  plugin_key TEXT NOT NULL,
  account_id TEXT NOT NULL,
  environment TEXT NOT NULL,
  check_kind TEXT NOT NULL,
  check_source TEXT NOT NULL DEFAULT 'scheduled' CHECK (check_source IN ('scheduled','manual','page_load','tool_call','deploy','startup')),
  status TEXT NOT NULL CHECK (status IN ('healthy','degraded','unhealthy','unreachable','auth_error')),
  started_at INTEGER NOT NULL,
  completed_at INTEGER NOT NULL,
  latency_ms INTEGER,
  http_status INTEGER,
  provider_request_id TEXT,
  error_code TEXT,
  error_message TEXT,
  details_json TEXT NOT NULL DEFAULT '{}',
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE IF NOT EXISTS agentsam_capabilities (
  capability_key TEXT PRIMARY KEY,
  domain TEXT NOT NULL,
  verb TEXT NOT NULL,
  description TEXT NOT NULL,
  is_mutating INTEGER NOT NULL DEFAULT 0 CHECK (is_mutating IN (0,1)),
  is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE IF NOT EXISTS agentsam_tools (
  id TEXT PRIMARY KEY DEFAULT ('ast_' || lower(hex(randomblob(8)))),
  tool_name TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  tool_category TEXT NOT NULL,
  handler_type TEXT NOT NULL DEFAULT 'mcp' CHECK (handler_type IN ('mcp','r2','github','terminal','http','proxy','ai','d1','hyperdrive','supabase','kv','durable_object','filesystem','browser_agentic','mybrowser','websearch','telemetry','eval','task.planner','task.organizer','task.manager','workspace.reader','cf','deploy','git','memory','notify','workflow','agent','browser','media','canvas','integrations','cms','completeful','vectorize')),
  description TEXT,
  input_schema TEXT,
  output_schema TEXT,
  linked_mcp_tool_id TEXT,
  mcp_service_url TEXT,
  handler_config TEXT DEFAULT '{}',
  intent_tags TEXT DEFAULT '[]',
  intent_category_tags TEXT,
  modes_json TEXT DEFAULT '["agent","plan","debug","multitask","ask"]',
  risk_level TEXT NOT NULL DEFAULT 'low' CHECK (risk_level IN ('low','medium','high','critical')),
  requires_approval INTEGER NOT NULL DEFAULT 0,
  requires_confirmation INTEGER NOT NULL DEFAULT 0,
  token_budget_per_call INTEGER,
  max_calls_per_session INTEGER,
  cost_per_call_usd REAL DEFAULT 0.0,
  is_active INTEGER NOT NULL DEFAULT 1,
  is_degraded INTEGER NOT NULL DEFAULT 0,
  failure_rate REAL DEFAULT 0.0,
  avg_latency_ms REAL,
  use_count INTEGER NOT NULL DEFAULT 0,
  last_used_at INTEGER,
  last_health_check INTEGER,
  sort_priority INTEGER DEFAULT 50,
  workspace_scope TEXT NOT NULL DEFAULT '["*"]',
  subagent_profile_id TEXT,
  schema_hint TEXT,
  notes TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch()),
  is_global INTEGER DEFAULT 1,
  tool_key TEXT,
  capability_key TEXT,
  handler_key TEXT,
  route_key TEXT,
  workflow_key TEXT,
  task_type TEXT DEFAULT 'tool_use',
  domain TEXT DEFAULT 'general',
  capability_tier TEXT DEFAULT 'common',
  internal_seo TEXT DEFAULT '',
  tool_code TEXT,
  oauth_visible INTEGER NOT NULL DEFAULT 0,
  dispatch_target TEXT NOT NULL DEFAULT 'internal',
  result_policy_json TEXT,
  caller_policy TEXT,
  cache_policy_json TEXT,
  updated_at_unix INTEGER,
  connector_visible INTEGER NOT NULL DEFAULT 0 CHECK (connector_visible IN (0,1)),
  connector_priority INTEGER,
  connector_access_class TEXT NOT NULL DEFAULT 'read' CHECK (connector_access_class IN ('read','write')),
  account_id TEXT,
  plugin_key TEXT,
  plugin_id TEXT REFERENCES agentsam_plugins(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS agentsam_tool_capabilities (
  tool_id TEXT NOT NULL REFERENCES agentsam_tools(id) ON DELETE CASCADE,
  capability_key TEXT NOT NULL REFERENCES agentsam_capabilities(capability_key),
  requirement_type TEXT NOT NULL DEFAULT 'required' CHECK (requirement_type='required'),
  is_primary INTEGER NOT NULL DEFAULT 0 CHECK (is_primary IN (0,1)),
  operations_json TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  PRIMARY KEY (tool_id, capability_key)
);

CREATE TABLE IF NOT EXISTS agentsam_tool_call_log (
  id TEXT PRIMARY KEY DEFAULT ('atcl_' || lower(hex(randomblob(8)))),
  account_id TEXT NOT NULL,
  agent_run_id TEXT,
  conversation_id TEXT,
  call_index INTEGER,
  tool_key TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('success','error','blocked','timeout','cancelled')),
  duration_ms INTEGER NOT NULL DEFAULT 0,
  error_code TEXT NOT NULL DEFAULT '',
  failure_origin TEXT CHECK (failure_origin IS NULL OR failure_origin IN ('model','tool','provider','platform','policy','user')),
  cost_usd REAL NOT NULL DEFAULT 0,
  input_tokens INTEGER NOT NULL DEFAULT 0,
  output_tokens INTEGER NOT NULL DEFAULT 0,
  cost_basis TEXT NOT NULL DEFAULT 'unknown' CHECK (cost_basis IN ('api_metered','external_subscription','platform_included','unknown')),
  source_client TEXT NOT NULL DEFAULT 'unknown',
  cache_hit INTEGER NOT NULL DEFAULT 0,
  external_execution INTEGER NOT NULL DEFAULT 1,
  result_source TEXT CHECK (result_source IS NULL OR result_source IN ('live','tool_cache')),
  created_at_unix INTEGER NOT NULL DEFAULT (unixepoch()),
  cache_eligible INTEGER NOT NULL DEFAULT 0 CHECK (cache_eligible IN (0,1)),
  cache_lookup_reason TEXT,
  cache_lookup_ms INTEGER,
  cache_key_hash TEXT,
  cache_input_hash TEXT
);
