// Generated by SAM deterministic code writer; source JSON Schemas are authoritative.
export interface SamGeneratedInputs {
  "sam.superbash": { "script"?: string; "scriptArtifactRef"?: string; "relativeCwd"?: string; "idempotencyKey"?: string; };
  "sam.script.save": { "script": string; "scriptId"?: string; "expectedVersion"?: number; "description"?: string; };
  "sam.script.get": { "scriptId": string; "version"?: number; };
  "cms.definition.list": { "kind"?: string; "status"?: string; };
  "cms.page.inspect": { "pageId": string; };
  "cms.page.createDraft": { "templateKey": string; "title": string; "path": string; };
  "cms.section.inspect": { "pageId": string; "sectionId": string; };
  "cms.section.create": { "pageId": string; "definitionKey": string; "expectedVersion": number; };
  "cms.section.updateDraft": { "sectionId": string; "settings": {  }; "expectedVersion": number; };
  "cms.section.duplicate": { "sectionId": string; "expectedVersion": number; };
  "cms.section.move": { "sectionId": string; "targetIndex": number; "expectedVersion": number; };
  "cms.section.visibility": { "sectionId": string; "visible": boolean; "expectedVersion": number; };
  "cms.section.remove": { "sectionId": string; "expectedVersion": number; };
  "cms.block.add": { "sectionId": string; "definitionKey": string; "parentBlockId"?: string; "expectedVersion": number; };
  "cms.block.update": { "blockId": string; "settings": {  }; "expectedVersion": number; };
  "cms.block.move": { "blockId": string; "targetIndex": number; "expectedVersion": number; };
  "cms.block.remove": { "blockId": string; "expectedVersion": number; };
  "cms.page.publish": { "pageId": string; "expectedVersion": number; };
  "media.asset.inspect": { "assetId": string; };
  "media.asset.upload": { "sourceArtifactRef": string; "filename": string; "contentType"?: string; };
  "media.asset.prepare": { "assetId": string; "operations": Array<{ "kind": "optimize" | "resize" | "crop" | "convert" | "trim_alpha" | "normalize_color"; "width"?: number; "height"?: number; "left"?: number; "top"?: number; "format"?: "png" | "jpeg" | "webp"; "quality"?: number; "fit"?: "inside" | "cover" | "contain" | "fill"; "allowUpscale"?: boolean; }>; "expectedVersion": number; "idempotencyKey"?: string; };
  "media.asset.job.status": { "jobId": string; };
  "media.asset.background.remove": { "assetId": string; "method"?: string; };
  "media.asset.versions.list": { "assetId": string; };
  "media.model.inspect": { "assetId": string; };
  "media.model.validate": { "assetId": string; };
  "media.model.optimize": { "assetId": string; "profile": "web" | "mobile" | "original_preserving"; "expectedVersion"?: number; };
  "product.artwork.preflight": { "assetId": string; "productId": string; "placement"?: string; };
  "cloudflare.r2.buckets.list": { "connectionRef"?: string; };
  "cloudflare.r2.objects.inventory": { "bucketRef": string; "prefix"?: string; "cursor"?: string; "pageSize"?: number; };
  "media.image.background.remove": { "assetId": string; "method"?: "flat_connected" | "subject_ai"; "tolerance"?: number; "idempotencyKey"?: string; };
  "media.image.generate": { "prompt": string; "model"?: string; "size"?: string; "variations"?: number; };
  "media.image.edit": { "prompt": string; "sourceArtifactRef": string; "model"?: string; "size"?: string; };
  "media.image.inspect": { "assetId": string; };
  "media.image.optimize": { "assetId": string; "idempotencyKey"?: string; "format"?: "png" | "webp" | "jpeg"; "quality"?: number; };
  "media.image.resize": { "assetId": string; "idempotencyKey"?: string; "format"?: "png" | "webp" | "jpeg"; "quality"?: number; "width"?: number; "height"?: number; "fit"?: "inside" | "cover" | "contain" | "fill"; "allowUpscale"?: boolean; };
  "media.image.crop": { "assetId": string; "idempotencyKey"?: string; "format"?: "png" | "webp" | "jpeg"; "quality"?: number; "left": number; "top": number; "width": number; "height": number; };
  "media.image.convert": { "assetId": string; "idempotencyKey"?: string; "format"?: "png" | "webp" | "jpeg"; "quality"?: number; };
  "media.image.trim_alpha": { "assetId": string; "idempotencyKey"?: string; "format"?: "png" | "webp" | "jpeg"; "quality"?: number; };
  "media.image.normalize_color": { "assetId": string; "idempotencyKey"?: string; "format"?: "png" | "webp" | "jpeg"; "quality"?: number; };
  "media.model.validateStructural": { "assetId": string; };
  "media.artwork.normalize": { "assetId": string; "profile": string; "idempotencyKey"?: string; };
  "media.artwork.vector.trace": { "assetId": string; "profile"?: string; };
  "media.artwork.svg.normalize": { "assetId": string; };
}
export type SamGeneratedToolName = keyof SamGeneratedInputs;
export interface SamGeneratedOperationResult { ok?: boolean; [key: string]: unknown }
export interface SamGeneratedAssetStore {
  getOwnedAsset(input: {assetId: string; accountId: string; actorId: string; installationId: string}): Promise<{id:string; accountId:string; bytes: Uint8Array}|null>;
  writeDerivative(input: {sourceAssetId: string; accountId: string; actorId: string; installationId: string; bytes: Uint8Array; preservation: "retain_original"; [key:string]: unknown}): Promise<{id:string}>;
}
