import { describe, expect, it } from "vitest";
import type { ContentAsset } from "../src/core/asset.js";
import { inferBrandAssociation, type BrandCandidate } from "../src/intelligence/brand-match.js";
import { findDuplicateGroups } from "../src/intelligence/duplicate-detect.js";
import { proposeSemanticAlias, slugify, deliveryFilename } from "../src/intelligence/semantic-name.js";
import { recommend } from "../src/intelligence/recommendations.js";
import { ragDocumentText } from "../src/intelligence/index.js";
import { seoReport } from "../src/intelligence/seo.js";

function asset(partial: Partial<ContentAsset>): ContentAsset {
  return {
    id: "ast_x",
    accountId: "acct",
    kind: "image",
    origin: "upload",
    state: "draft",
    source: { type: "upload" },
    providerRefs: [],
    tags: [],
    variants: [],
    usage: [],
    provenance: { history: [] },
    createdBy: { type: "human" },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    ...partial,
  };
}

const FICTIONAL_CANDIDATES: BrandCandidate[] = [
  { brandId: "northwind-garage", name: "Northwind Garage", keywords: ["garage", "car", "fuel"] },
  { brandId: "cedar-studio", name: "Cedar Studio", keywords: ["animal", "studio"] },
];

describe("intelligence", () => {
  it("slugifies + proposes semantic aliases", () => {
    expect(slugify("AgentSam Workbench Review — Mobile!")).toBe(
      "agentsam-workbench-review-mobile",
    );
    const a = asset({
      brandId: "northwind-garage",
      title: "workbench review",
      role: "screenshot",
      filename: "IMG_5933.PNG",
    });
    expect(proposeSemanticAlias(a)).toBe("northwind-garage-workbench-review-screenshot");
    expect(deliveryFilename("emblem", 1280, "avif")).toBe("emblem-1280.avif");
  });

  it("infers brand association with ScoreCard evidence (not BrandPack authority)", async () => {
    const inferred = await inferBrandAssociation(
      asset({ tags: ["garage", "car"], title: "logo motif" }),
      FICTIONAL_CANDIDATES,
      { computedAt: "2026-09-27T00:00:00.000Z" },
    );
    expect(inferred?.brandId).toBe("northwind-garage");
    expect(inferred?.scoreCard.kind).toBe("brand-affinity");
    expect(inferred?.scoreCard.weightsVersion).toBe("brand-affinity.v1");
    expect(inferred?.scoreCard.score).toBeGreaterThan(0);
    expect(inferred?.evidence.length).toBeGreaterThan(0);
    expect(inferred?.explanation).toContain("brand-affinity:");

    const explicit = await inferBrandAssociation(
      asset({ brandId: "cedar-studio", tags: ["garage", "car"] }),
      FICTIONAL_CANDIDATES,
      { computedAt: "2026-09-27T00:00:00.000Z" },
    );
    expect(explicit?.brandId).toBe("cedar-studio");
    expect(explicit?.stage).toBe("explicit");
    expect(explicit?.confidence).toBeGreaterThan(0);
  });

  it("groups exact duplicates by hash", () => {
    const groups = findDuplicateGroups([
      asset({ id: "a1", intelligence: { machine: { hash: "h1" } } }),
      asset({ id: "a2", intelligence: { machine: { hash: "h1" } } }),
      asset({ id: "a3", intelligence: { machine: { hash: "h2" } } }),
    ]);
    expect(groups).toHaveLength(1);
    expect(groups[0]?.assetIds).toEqual(["a1", "a2"]);
  });

  it("recommends optimization for heavy images without approved derivatives", () => {
    const heavy = asset({ bytes: 4_800_000, state: "live", filename: "big.png" });
    const recs = recommend(heavy);
    expect(recs.map((r) => r.id)).toContain("optimize");
    expect(recs.map((r) => r.id)).toContain("alt");

    const optimized = asset({
      bytes: 4_800_000,
      alt: "Emblem on garage wall",
      semanticAlias: "nw-emblem",
      tags: ["logo"],
      variants: [{ name: "public", format: "avif", bytes: 140_000, approved: true }],
    });
    expect(recommend(optimized).map((r) => r.id)).not.toContain("optimize");
  });

  it("scores SEO against semantic naming and weight", () => {
    const bad = seoReport(asset({ filename: "IMG_5933.PNG", bytes: 4_800_000 }));
    const good = seoReport(
      asset({
        semanticAlias: "nw-emblem-garage",
        alt: "Northwind emblem painted on a garage door",
        caption: "Emblem",
        bytes: 120_000,
        variants: [{ name: "og", format: "webp", bytes: 90_000, approved: true }],
      }),
    );
    expect(good.score).toBeGreaterThan(bad.score);
  });

  it("builds a facts-first RAG document", () => {
    const text = ragDocumentText(
      asset({
        state: "live",
        alt: "Black hourglass mark",
        rating: -1,
        brandId: "northwind-garage",
        tags: ["logo", "hourglass"],
        usage: [{ app: "northwind-garage", surface: "home.hero", live: true }],
        provenance: { history: [], generation: { model: "img-gen-1", prompt: "hourglass logo" } },
      }),
    );
    expect(text).toContain("used by: northwind-garage/home.hero");
    expect(text).toContain("human rating: -1");
    expect(text).toContain("generated by: img-gen-1");
  });
});
