import { describe, expect, it } from "vitest";
import type { ContentAsset } from "../src/core/asset.js";
import { matchBrand } from "../src/intelligence/brand-match.js";
import { findDuplicateGroups } from "../src/intelligence/duplicate-detect.js";
import { proposeSemanticAlias, slugify, deliveryFilename } from "../src/intelligence/semantic-name.js";
import { recommend } from "../src/intelligence/recommendations.js";
import { ragDocumentText } from "../src/intelligence/index.js";
import { seoReport } from "../src/intelligence/seo.js";

function asset(partial: Partial<ContentAsset>): ContentAsset {
  return {
    id: "ast_x",
    accountId: "acct",
    kind: "image",
    origin: "upload",
    state: "draft",
    source: { type: "upload" },
    providerRefs: [],
    tags: [],
    variants: [],
    usage: [],
    provenance: { history: [] },
    createdBy: { type: "human" },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    ...partial,
  };
}

describe("intelligence", () => {
  it("slugifies + proposes semantic aliases", () => {
    expect(slugify("AgentSam Workbench Review — Mobile!")).toBe(
      "agentsam-workbench-review-mobile",
    );
    const a = asset({
      brandId: "fuel-free-time",
      title: "workbench review",
      role: "screenshot",
      filename: "IMG_5933.PNG",
    });
    expect(proposeSemanticAlias(a)).toBe("fuel-free-time-workbench-review-screenshot");
    expect(deliveryFilename("emblem", 1280, "avif")).toBe("emblem-1280.avif");
  });

  it("matches brands deterministically and honors explicit associations", () => {
    const packs = [
      { brandId: "fft", name: "Fuel & Free Time", keywords: ["garage", "car", "fuel"] },
      { brandId: "iam", name: "InnerAnimalMedia", keywords: ["animal", "studio"] },
    ];
    const inferred = matchBrand(asset({ tags: ["garage", "car"], title: "logo motif" }), packs);
    expect(inferred?.brandId).toBe("fft");

    const explicit = matchBrand(asset({ brandId: "iam", tags: ["garage", "car"] }), packs);
    expect(explicit?.brandId).toBe("iam");
    expect(explicit?.confidence).toBe(1);
  });

  it("groups exact duplicates by hash", () => {
    const groups = findDuplicateGroups([
      asset({ id: "a1", intelligence: { machine: { hash: "h1" } } }),
      asset({ id: "a2", intelligence: { machine: { hash: "h1" } } }),
      asset({ id: "a3", intelligence: { machine: { hash: "h2" } } }),
    ]);
    expect(groups).toHaveLength(1);
    expect(groups[0]?.assetIds).toEqual(["a1", "a2"]);
  });

  it("recommends optimization for heavy images without approved derivatives", () => {
    const heavy = asset({ bytes: 4_800_000, state: "live", filename: "big.png" });
    const recs = recommend(heavy);
    expect(recs.map((r) => r.id)).toContain("optimize");
    expect(recs.map((r) => r.id)).toContain("alt");

    const optimized = asset({
      bytes: 4_800_000,
      alt: "Emblem on garage wall",
      semanticAlias: "fft-emblem",
      tags: ["logo"],
      variants: [{ name: "public", format: "avif", bytes: 140_000, approved: true }],
    });
    expect(recommend(optimized).map((r) => r.id)).not.toContain("optimize");
  });

  it("scores SEO against semantic naming and weight", () => {
    const bad = seoReport(asset({ filename: "IMG_5933.PNG", bytes: 4_800_000 }));
    const good = seoReport(
      asset({
        semanticAlias: "fft-emblem-garage",
        alt: "FFT emblem painted on a garage door",
        caption: "Emblem",
        bytes: 120_000,
        variants: [{ name: "og", format: "webp", bytes: 90_000, approved: true }],
      }),
    );
    expect(good.score).toBeGreaterThan(bad.score);
  });

  it("builds a facts-first RAG document", () => {
    const text = ragDocumentText(
      asset({
        state: "live",
        alt: "Black hourglass mark",
        rating: -1,
        brandId: "fft",
        tags: ["logo", "hourglass"],
        usage: [{ app: "fuel-free-time", surface: "home.hero", live: true }],
        provenance: { history: [], generation: { model: "img-gen-1", prompt: "hourglass logo" } },
      }),
    );
    expect(text).toContain("used by: fuel-free-time/home.hero");
    expect(text).toContain("human rating: -1");
    expect(text).toContain("generated by: img-gen-1");
  });
});
