#!/usr/bin/env python3
"""brand_compliance.py v2 - third-party-mark, wording, and license hygiene.

Python stdlib only. Policy lives in rules.json next to this file.
This tool flags common risk patterns. It is not legal advice and it does not
certify that anything is cleared, licensed, or compliant.

Modes
  scan    report every finding. Never writes.
  check   like scan; exit 1 if any ERROR remains (use in CI).
  apply   dry-run by default (throwaway git worktree + diff stat);
          add --write to change the real tree. Requires a clean git tree.
          --refresh-trademarks overwrites TRADEMARKS.md even if hand-edited.

What apply fixes automatically (idempotent)
  renames from rules.json, UNLICENSED -> MIT (+ LICENSE files), denied keywords,
  affiliation tail on package descriptions that name a mark, known phrase
  rewrites, TRADEMARKS.md, README attribution notices (refreshed in place).
What it only reports
  names that embed a mark in skills/packages/apps dirs, recreated logos, brand
  icons, partnership/guarantee wording, vendored content without provenance,
  dependency license risks.

Never edits package-lock.json. After apply --write run:
  npm install --package-lock-only
"""
import argparse
import fnmatch
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
TEXT_EXT = {
    ".js", ".mjs", ".cjs", ".ts", ".tsx", ".jsx", ".json", ".jsonc", ".md", ".html",
    ".yaml", ".yml", ".toml", ".sh", ".py", ".css", ".txt", ".example",
}
FONT_EXT = {".woff", ".woff2", ".ttf", ".otf"}
MAX_BYTES = 2_000_000
GEN_MARKER = "<!-- generated by brand_compliance"


# ----------------------------------------------------------------- plumbing
def run_git(root, *args, check=True):
    res = subprocess.run(["git", "-C", str(root), *args], capture_output=True, text=True)
    if check and res.returncode != 0:
        raise SystemExit(f"git {' '.join(args)} failed: {res.stderr.strip()}")
    return res


def tracked(root):
    out = subprocess.run(["git", "-C", str(root), "ls-files", "-z"], capture_output=True)
    names = out.stdout.decode("utf-8", "replace").split("\0")
    return [p for p in names if p and (root / p).exists()]


def load_rules(path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def is_excluded(rel, rules):
    return any(fnmatch.fnmatch(rel, pat) for pat in rules["exclude"])


def read_text(path):
    try:
        if path.stat().st_size > MAX_BYTES:
            return None
        return path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return None


def text_files(root, rules):
    for rel in tracked(root):
        if is_excluded(rel, rules):
            continue
        p = root / rel
        if p.suffix.lower() not in TEXT_EXT or not p.is_file():
            continue
        text = read_text(p)
        if text is not None:
            yield rel, p, text


def detect_indent(text):
    m = re.search(r"\n([ \t]+)\"", text)
    return m.group(1) if m else "  "


def load_json(path):
    text = path.read_text(encoding="utf-8")
    return json.loads(text), detect_indent(text), text.endswith("\n")


def dump_json(data, indent, trailing_newline):
    return json.dumps(data, indent=indent, ensure_ascii=False) + ("\n" if trailing_newline else "")


def package_jsons(root, rules):
    for rel in tracked(root):
        if Path(rel).name != "package.json" or is_excluded(rel, rules):
            continue
        p = root / rel
        try:
            data, _, _ = load_json(p)
        except (ValueError, OSError):
            continue
        if isinstance(data, dict) and "name" in data:
            yield rel, p, data


def publishable(data):
    return data.get("private") is not True


def oxford(items):
    items = list(items)
    if len(items) < 3:
        return " and ".join(items)
    return ", ".join(items[:-1]) + ", and " + items[-1]


def repo_urls(root):
    data, _, _ = load_json(root / "package.json")
    home = (data.get("homepage") or "").split("#")[0].rstrip("/")
    issues = (data.get("bugs") or {}).get("url") or (home + "/issues" if home else "")
    return (f"{home}/blob/main/TRADEMARKS.md" if home else "TRADEMARKS.md"), issues


def owner_name(root):
    lic = root / "LICENSE"
    if lic.exists():
        m = re.search(r"Copyright \(c\) \d{4}\s+(.+)", lic.read_text(encoding="utf-8"))
        if m:
            return m.group(1).strip()
    return "the project owners"


# -------------------------------------------------------------------- marks
class Marks:
    def __init__(self, rules):
        self.rules = rules
        self.list = rules["marks"]
        self.by_term = {}
        for m in self.list:
            for t in m["terms"]:
                self.by_term[t.lower()] = m
        strong = [t for m in self.list if not m.get("generic") for t in m["terms"]]
        alt = "|".join(sorted((re.escape(t) for t in strong), key=len, reverse=True))
        self.alt = alt
        r = rules
        self.compound_err = re.compile(rf"\b(?:{alt})-(?:{r['compound_suffixes_error']})\b", re.I)
        self.compound_warn = re.compile(
            rf"\b(?:{alt})-(?:{r['compound_suffixes_hyphen_warn']})\b"
            rf"|\b(?:{alt}) (?:{r['compound_suffixes_space_warn']})\b"
            rf"|\bpowered by (?:{alt})\b", re.I)
        self.strong_re = re.compile(rf"\b(?:{alt})\b", re.I)
        c = r["claims"]
        self.partner_res = [re.compile(x.replace("{marks}", alt), re.I) for x in c["partnership_regexes"]]
        self.guarantee_res = [re.compile(x, re.I) for x in c["guarantee_regexes"]]
        self.negations = [n.lower() for n in c["negation_markers"]]

    @staticmethod
    def tokens(s):
        return re.findall(r"[a-z0-9]+", s.lower())

    def in_name(self, s):
        seen, out = set(), []
        for t in self.tokens(s):
            m = self.by_term.get(t)
            if m and m["name"] not in seen:
                seen.add(m["name"])
                out.append(m)
        return out

    def mentioned(self, text):
        return sorted({m["name"] for m in self.list if not m.get("generic")
                       and any(re.search(rf"\b{re.escape(t)}\b", text, re.I) for t in m["terms"])})

    def affiliation_tail(self, desc):
        found = [m for m in self.list if not m.get("generic")
                 and any(re.search(rf"\b{re.escape(t)}\b", desc, re.I) for t in m["terms"])]
        if not found:
            return None
        names = [m.get("display") or m["name"] for m in found]
        return self.rules["description_suffix"].replace("{display}", oxford(names))


# --------------------------------------------------------------------- scan
def finding(code, sev, path, msg, line=None):
    return {"code": code, "severity": sev, "path": path, "line": line, "msg": msg}


def name_allowed(rel, rules):
    return any(fnmatch.fnmatch(rel, g) for g in rules["name_allow"])


def scan(root, rules):
    out = []
    mk = Marks(rules)
    files = tracked(root)
    spdx = rules["license"]["spdx"]
    bad_lic = set(rules["license"]["replace"])
    marker = rules["notice_marker"]
    logo_res = [re.compile(p, re.I) for p in rules["logo_filename_patterns"]]
    lucide = set(rules["lucide_brand_icons"])

    # names, bins, keywords of publishable packages
    for rel, _, data in package_jsons(root, rules):
        if not publishable(data):
            continue
        lic = data.get("license")
        if lic in bad_lic or not lic:
            out.append(finding("E001", "error", rel, f"public package license is {lic!r}; expected {spdx}"))
        if not name_allowed(rel, rules):
            for m in mk.in_name(str(data.get("name", ""))):
                out.append(finding("E002", "error", rel, f"package name contains the mark {m['name']}: {data['name']}"))
            bins = data.get("bin")
            for b in (bins.keys() if isinstance(bins, dict) else []):
                for m in mk.in_name(b):
                    out.append(finding("E002", "error", rel, f"bin name contains the mark {m['name']}: {b}"))
        for kw in data.get("keywords", []) or []:
            m = mk.by_term.get(str(kw).lower())
            if m:
                if m.get("keywords") == "deny":
                    out.append(finding("E003", "error", rel, f"keyword uses the mark {m['name']}: {kw}"))
                else:
                    out.append(finding("W205", "warn", rel, f"keyword uses the mark {m['name']} (descriptive; review): {kw}"))
        desc = str(data.get("description", ""))
        tail = mk.affiliation_tail(desc)
        if tail and "not affiliated" not in desc.lower():
            out.append(finding("W102", "warn", rel, "description names a mark without an affiliation tail"))

    # app manifests
    for rel in files:
        if Path(rel).name == "agentsam.app.json" and not is_excluded(rel, rules):
            try:
                data, _, _ = load_json(root / rel)
            except ValueError:
                continue
            for key in ("id", "package"):
                for m in mk.in_name(str(data.get(key, ""))):
                    out.append(finding("E002", "error", rel, f"app {key} contains the mark {m['name']}: {data[key]}"))

    # catalog ids
    for rel in ("skills/catalog.json", "protocol/presets/catalog.json"):
        p = root / rel
        if not p.exists():
            continue
        data, _, _ = load_json(p)
        ids = [s.get("id", "") for s in data.get("skills", [])]
        for section in ("presets", "addons"):
            ids += list((data.get(section) or {}).keys())
        allowed_catalog_ids = set(rules.get("catalog_id_allow", []))
        for i in ids:
            if i in allowed_catalog_ids:
                continue
            for m in mk.in_name(i):
                out.append(finding("E007", "error", rel, f"catalog id contains the mark {m['name']}: {i}"))

    # directory names under skills/, packages/, apps/ (and one level deeper for packages)
    seen_dirs = set()
    for rel in files:
        parts = rel.split("/")
        for depth in (2, 3):
            if len(parts) > depth and parts[0] in ("skills", "packages", "apps"):
                d = "/".join(parts[:depth])
                if parts[0] == "packages" and depth == 3 and parts[1] not in ("connectors", "providers"):
                    continue
                if d in seen_dirs or name_allowed(d, rules) or parts[depth - 1].startswith("."):
                    continue
                seen_dirs.add(d)
                for m in mk.in_name(parts[depth - 1]):
                    out.append(finding("E008", "error", d, f"directory name contains the mark {m['name']}"))

    # logo-like file names
    for rel in files:
        if is_excluded(rel, rules):
            continue
        if any(rx.search(rel) for rx in logo_res):
            out.append(finding("E005", "error", rel, "file name suggests a third-party logo/icon asset"))

    # text-level checks
    for rel, _, text in text_files(root, rules):
        is_own_notice = rel == "TRADEMARKS.md"
        if rel.endswith((".md", ".html", ".json")):
            for i, line in enumerate(text.splitlines(), 1):
                low = line.lower()
                if marker in line or is_own_notice:
                    continue
                if mk.compound_err.search(line):
                    out.append(finding("E004", "error", rel, "brand compound: " + line.strip()[:100], i))
                elif mk.compound_warn.search(line):
                    out.append(finding("W103", "warn", rel, "brand-style phrase: " + line.strip()[:100], i))
                if not any(n in f" {low} " for n in mk.negations):
                    hit = next((rx for rx in mk.partner_res if rx.search(line)), None)
                    if hit and mk.strong_re.search(line):
                        out.append(finding("E010", "error", rel, "partnership/endorsement wording: " + line.strip()[:100], i))
                if any(rx.search(line) for rx in mk.guarantee_res):
                    out.append(finding("W301", "warn", rel, "guarantee/certification wording: " + line.strip()[:100], i))
        if rel.endswith((".ts", ".tsx", ".jsx", ".js")):
            for m in re.finditer(r"import\s*\{([^}]*)\}\s*from\s*['\"]lucide-react['\"]", text):
                hit = lucide & {x.strip().split(" as ")[0] for x in m.group(1).split(",")}
                if hit:
                    out.append(finding("W201", "warn", rel, "imports brand-logo icon(s) from lucide-react: " + ", ".join(sorted(hit))))
        if rel.endswith((".ts", ".tsx", ".jsx", ".js", ".html", ".svg", ".css")):
            low = text.lower()
            for cs in rules["brand_color_sets"]:
                if sum(1 for h in cs["hexes"] if h in low) >= cs["min_hits"]:
                    out.append(finding("W202", "warn", rel, f"{cs['mark']} brand colors together (possible recreated logo); use the owner's official asset or a neutral icon"))
        if rel.endswith(".html"):
            for m in re.finditer(r"<(title|h1)[^>]*>([^<]*)<", text, re.I):
                if mk.strong_re.search(m.group(2)):
                    out.append(finding("W104", "warn", rel, f"<{m.group(1).lower()}> contains a mark: {m.group(2).strip()[:80]}"))
            if fnmatch.fnmatch(rel, rules["site_page_glob"]) and "/_sections/" not in rel \
                    and mk.mentioned(text) and not re.search(r"trademark", text, re.I):
                out.append(finding("W105", "warn", rel, "public page names marks without a trademark/attribution line"))
        if Path(rel).name.lower() == "readme.md" and mk.mentioned(text) and marker not in text \
                and not rel.startswith("docs/") and "/reference/" not in rel and "/examples/" not in rel:
            out.append(finding("W101", "warn", rel, "README names marks without the attribution notice"))

    # own-text promise lint
    tm = root / "TRADEMARKS.md"
    if not tm.exists():
        out.append(finding("E006", "error", "TRADEMARKS.md", "missing"))
    else:
        low = tm.read_text(encoding="utf-8").lower()
        for phrase in rules["claims"]["own_text_denylist"]:
            if phrase in low:
                out.append(finding("E012", "error", "TRADEMARKS.md", f"promissory/claim wording: {phrase!r}"))

    # vendored content without provenance
    prov = set(rules["provenance_files"])
    vdirs = {}
    for rel in files:
        parts = rel.split("/")
        for i, seg in enumerate(parts[:-1]):
            if seg.lower() in rules["vendored_dir_names"]:
                vdirs.setdefault("/".join(parts[:i + 1]), "/".join(parts[:i]))
                break
    for vd, parent in sorted(vdirs.items()):
        if any(fnmatch.fnmatch(vd, g) for g in rules.get("provenance_exempt", [])):
            continue
        siblings = {Path(f).name.lower() for f in files if str(Path(f).parent).replace("\\", "/") == (parent or ".")}
        inside = {Path(f).name.lower() for f in files if f.startswith(vd + "/") and "/" not in f[len(vd) + 1:]}
        if not ((siblings | inside) & prov):
            out.append(finding("W203", "warn", vd, "vendored/reference content with no SOURCE/LICENSE/NOTICE beside it"))

    # fonts
    fonts = [f for f in files if Path(f).suffix.lower() in FONT_EXT]
    by_dir = {}
    for f in fonts:
        by_dir.setdefault(str(Path(f).parent), []).append(f)
    for d, fl in sorted(by_dir.items()):
        out.append(finding("I202", "info", d, f"{len(fl)} font file(s); record their license/source"))

    # integration-target identifiers kept on purpose
    term = rules["integration_path_term"].lower()
    for p in files:
        if term in p.lower() and not is_excluded(p, rules):
            out.append(finding("I201", "info", p, "integration-target identifier in path (kept; list for counsel review)"))

    out.extend(license_audit(root, rules))
    return out


def license_audit(root, rules):
    lock = root / "package-lock.json"
    if not lock.exists():
        return []
    cfg = rules["license_audit"]
    data = json.loads(lock.read_text(encoding="utf-8"))
    out = []
    for key, v in data.get("packages", {}).items():
        if not key.startswith("node_modules/") or v.get("link"):
            continue
        name = key.split("node_modules/")[-1]
        if any(fnmatch.fnmatch(name, g) for g in cfg["allow_name_globs"]):
            continue
        lic = v.get("license")
        if isinstance(lic, dict):
            lic = lic.get("type")
        if isinstance(lic, list):
            lic = " OR ".join(map(str, lic))
        scope = "dev" if v.get("dev") else "runtime"
        if not lic:
            out.append(finding("W403", "warn", name, f"dependency ({scope}) has no license field in the lockfile"))
        elif any(r in str(lic).upper() for r in cfg["risky"]):
            out.append(finding("W401", "warn", name, f"dependency ({scope}) license {lic}; review before redistributing"))
        elif any(r in str(lic).upper() for r in cfg["info"]):
            out.append(finding("I402", "info", name, f"dependency ({scope}) license {lic}"))
    return out


def print_report(findings, as_json):
    if as_json:
        print(json.dumps(findings, indent=2))
        return
    order = {"error": 0, "warn": 1, "info": 2}
    by_code = {}
    for f in findings:
        by_code.setdefault(f["code"], []).append(f)
    for code in sorted(by_code, key=lambda c: (order[by_code[c][0]["severity"]], c)):
        rows = by_code[code]
        print(f"\n[{code}] {rows[0]['severity'].upper()}  x{len(rows)}")
        limit = 8 if rows[0]["severity"] != "info" else 3
        for f in rows[:limit]:
            loc = f"{f['path']}:{f['line']}" if f["line"] else f["path"]
            print(f"   {loc}  {f['msg']}")
        if len(rows) > limit:
            print(f"   ... {len(rows) - limit} more")
    c = {s: sum(1 for f in findings if f["severity"] == s) for s in order}
    print(f"\nsummary: {c['error']} error, {c['warn']} warn, {c['info']} info")


# -------------------------------------------------------------------- apply
def token_regex(old):
    return re.compile(r"(?<![\w-])" + re.escape(old) + r"(?![\w-])")


def build_trademarks(root, rules, mk):
    attributions = []
    for m in mk.list:
        if m.get("attribution"):
            prod = oxford(m.get("products", []))
            attributions.append(f"{m['attribution']}" + (f" {prod} are names of {m['name']} products and services." if prod else ""))
    primaries = [m.get("display") or m["name"] for m in mk.list if m.get("attribution")]
    others = [m["name"] for m in mk.list if not m.get("attribution")]
    body = (HERE / "TRADEMARKS.template.md").read_text(encoding="utf-8")
    _, issues = repo_urls(root)
    return (body.replace("{{PROJECT}}", rules["project_name"])
                .replace("{{OWNER}}", owner_name(root))
                .replace("{{AFFILIATE_LIST}}", oxford(primaries) or "any named company")
                .replace("{{ATTRIBUTIONS}}", "\n\n".join(attributions))
                .replace("{{OTHER_MARKS}}", oxford(others))
                .replace("{{ISSUES_URL}}", issues or "the project issue tracker"))


def apply_fixes(root, rules, refresh_trademarks=False):
    log = []
    mk = Marks(rules)

    for rule in rules["renames"]:
        for old, new in rule.get("moves", []):
            if (root / old).exists() and not (root / new).exists():
                (root / new).parent.mkdir(parents=True, exist_ok=True)
                run_git(root, "mv", old, new)
                log.append(f"git mv {old} -> {new}")

    counts = {r["id"]: 0 for r in rules["renames"]}
    for rel, p, text in list(text_files(root, rules)):
        new_text = text
        for rule in rules["renames"]:
            only = rule.get("only_files")
            if only and rel not in only:
                continue
            for old, new in rule["tokens"]:
                new_text, n = token_regex(old).subn(new, new_text)
                counts[rule["id"]] += n
        if new_text != text:
            p.write_text(new_text, encoding="utf-8")
    for rid, n in counts.items():
        log.append(f"rename[{rid}]: {n} token replacement(s)")

    lic_text = (root / rules["license"]["text_source"]).read_text(encoding="utf-8")
    spdx, bad = rules["license"]["spdx"], set(rules["license"]["replace"])
    for rel, p, data in package_jsons(root, rules):
        if not publishable(data):
            continue
        _, indent, nl = load_json(p)
        changed = []
        if data.get("license") in bad or not data.get("license"):
            data["license"] = spdx
            changed.append("license")
            lic_path = p.parent / "LICENSE"
            if p.parent != root and not lic_path.exists():
                lic_path.write_text(lic_text, encoding="utf-8")
                changed.append("LICENSE file")
        if isinstance(data.get("keywords"), list):
            kept = [k for k in data["keywords"]
                    if not (mk.by_term.get(str(k).lower()) or {}).get("keywords") == "deny"]
            if kept != data["keywords"]:
                data["keywords"] = kept
                changed.append("keywords")
        desc = data.get("description")
        if isinstance(desc, str) and "not affiliated" not in desc.lower():
            tail = mk.affiliation_tail(desc)
            if tail:
                data["description"] = desc.rstrip() + ("" if desc.rstrip()[-1:] in ".!?" else ".") + " " + tail
                changed.append("description")
        if changed:
            p.write_text(dump_json(data, indent, nl), encoding="utf-8")
            log.append(f"{rel}: {', '.join(changed)}")

    for rel, p, text in list(text_files(root, rules)):
        new_text = text
        for rw in rules["phrase_rewrites"]:
            if p.suffix.lower() in rw["ext"]:
                new_text = re.sub(rw["pattern"], rw["replace"], new_text)
        if new_text != text:
            p.write_text(new_text, encoding="utf-8")
            log.append(f"{rel}: phrase rewrite")

    tm = root / "TRADEMARKS.md"
    cur = tm.read_text(encoding="utf-8") if tm.exists() else None
    if cur is None or refresh_trademarks or cur.startswith(GEN_MARKER):
        new = build_trademarks(root, rules, mk)
        if new != cur:
            tm.write_text(new, encoding="utf-8")
            log.append("TRADEMARKS.md " + ("created" if cur is None else "updated"))
    elif cur is not None:
        log.append("TRADEMARKS.md left alone (hand-edited; use --refresh-trademarks to regenerate)")
    rp = root / "package.json"
    data, indent, nl = load_json(rp)
    files = data.get("files")
    if isinstance(files, list) and "TRADEMARKS.md" not in files:
        files.append("TRADEMARKS.md")
        rp.write_text(dump_json(data, indent, nl), encoding="utf-8")
        log.append("package.json: files += TRADEMARKS.md")

    marker = rules["notice_marker"]
    url, _ = repo_urls(root)
    n_cf = rules["readme_notice_cloudflare"].format(trademarks_url=url)
    n_gen = rules["readme_notice_generic"].format(trademarks_url=url)
    block_re = re.compile(re.escape(marker) + r"\n> [^\n]*\n")
    added = refreshed = 0
    for rel, p, text in list(text_files(root, rules)):
        if Path(rel).name.lower() != "readme.md":
            continue
        if rel.startswith("docs/") or "/reference/" in rel or "/examples/" in rel:
            continue
        mentioned = mk.mentioned(text)
        if not mentioned:
            continue
        notice = n_cf if "Cloudflare" in mentioned else n_gen
        block = f"{marker}\n{notice}\n"
        if marker in text:
            new_text = block_re.sub(lambda _m: block, text, count=1)
            if new_text != text:
                p.write_text(new_text, encoding="utf-8")
                refreshed += 1
        else:
            p.write_text(text.rstrip("\n") + f"\n\n{block}", encoding="utf-8")
            added += 1
    log.append(f"README attribution notices: {added} added, {refreshed} refreshed")
    return log


def cmd_apply(root, rules, write, refresh):
    if run_git(root, "status", "--porcelain").stdout.strip():
        raise SystemExit("working tree is not clean; commit or stash first (git is the backup).")
    if write:
        print("\n".join(apply_fixes(root, rules, refresh)))
        print("\nnext: npm install --package-lock-only && npm run verify")
        return
    tmp = Path(tempfile.mkdtemp(prefix="brand-compliance-"))
    wt = tmp / "wt"
    try:
        run_git(root, "worktree", "add", "--detach", str(wt), "HEAD")
        log = apply_fixes(wt, rules, refresh)
        print("DRY RUN (nothing in your tree changed). Planned actions:\n")
        print("\n".join(log))
        run_git(wt, "add", "-A")
        stat = run_git(wt, "diff", "--cached", "--stat", "-M").stdout.strip().splitlines()
        print("\n" + "\n".join(stat[-1:]))
        print("\nre-run with --write to apply.")
    finally:
        run_git(root, "worktree", "remove", "--force", str(wt), check=False)
        shutil.rmtree(tmp, ignore_errors=True)


# --------------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("mode", choices=["scan", "check", "apply"])
    ap.add_argument("--root", default=".")
    ap.add_argument("--rules", default=str(HERE / "rules.json"))
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--refresh-trademarks", action="store_true")
    args = ap.parse_args()
    root = Path(args.root).resolve()
    if not (root / ".git").exists():
        raise SystemExit(f"{root} is not a git repository root")
    rules = load_rules(args.rules)
    if args.mode == "apply":
        cmd_apply(root, rules, args.write, args.refresh_trademarks)
        return
    findings = scan(root, rules)
    print_report(findings, args.json)
    if args.mode == "check" and any(f["severity"] == "error" for f in findings):
        sys.exit(1)


if __name__ == "__main__":
    main()
