export { KnowledgeClient } from "./client.js";
export { KNOWLEDGE_OPERATIONS, assertContextPack, assertRetrievalQuery } from "./contracts.js";
export { buildRetrievalPlan } from "./retrieval.js";
export { createContextPack, estimateTokens } from "./context-pack.js";
export { defaultConfig, validateConfig, readConfig, initRepository, repositoryRoot, scopeKey, cacheNamespace } from './config.js';
export { planIndex, runIndex, retrieve, embeddingProfileId } from './engine.js';
export { openSqliteStore } from './stores/sqlite.js';
export { createPostgresStore, openPostgresStore, postgresSchema } from './stores/postgres.js';
export { createGeminiEmbedder } from './providers/gemini.js';
export { compareObservations } from './evolution.js';
